env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[b9455bd3688144a717e82c52d90608feb44db92bd1ad6675072685da57663b03f537e1f798e4dec1a1f46d0bea9064a3]"
    bot_api: "ENCRYPTED[203cc642df3a41c42a5477fa3569a9a45b8bd4a5720dfa717e29d5e01127dc69799c5a2c74270c0f9c8d1109c4143222]"
    chat_id: "ENCRYPTED[73b4d3a4d0f6c12ba795457d76601753486b73b24a4094a0ddc6276567b1623dccd9d391e559c70f861c7c60a09af9ed]"

# store information about git here
    gmail: ehteshammalik18998@gmail.com

# User Version ( dont touch )
    user_version: 2 # lets start from 1

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_cc_background_script: # To download cc in background
      - git clone https://$CIRRUS_REPO_OWNER:$github_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash download_cc # cc download script
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_cc_script: # Upload cc to cloud foreground
      - bash upload_cc # cc uploading script
