#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

apt install wget pigz

cd /tmp # Where to download cccahe

echo "|| Downloading CCACHE ||"
time wget https://nebula.uvscuti.workers.dev/0:/ccache_backup.zip.001
time wget https://nebula.uvscuti.workers.dev/0:/ccache_backup.zip.002

echo "|| Extracting CCACHE ||"
7za x ccache_backup.zip.001
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file
rm -rf ccache_backup.zip.*

# fix
echo "" > /etc/mtab
