#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

tg () {
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$1&chat_id=${chat_id}"
}

tg "Build started!
https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
SECONDS=0

##some of my work
git config --global user.name "wHoEMi"
git config --global user.email "ehteshammalik18998@gmail.com"

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --depth=1 --no-repo-verify -u https://github.com/AtomXCLO/android_manifest -b sc-v2 -g default,-mips,-darwin,-notdefault

# Local manifest
git clone https://github.com/wHo-EM-i/manifest.git --depth 1 -b atomx .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_lavender -b 10 device/xiaomi/lavender
#git clone --depth=1 https://github.com/ImSpiDy/vendor_xiaomi_lavender -b 10 vendor/xiaomi/lavender
#git clone --depth=1 https://github.com/stormbreaker-project/kernel_xiaomi_lavender -b oldcam-hmp kernel/xiaomi/lavender
#git clone -b master --depth=1 https://github.com/kdrag0n/proton-clang.git prebuilts/clang/host/linux-x86/clang-proton

tg "Cloned all Sources Successfully! Time Took: $(($SECONDS / 60))min and $(($SECONDS % 60))sec "
