#!/bin/bash

cd /tmp

up () {
  if [ -e $1 ]; then
  echo "uploading $1"
	curl -4 --retry 18 --raw --upload-file $1 https://temp.sh/$(basename $1); echo
	# 3 days, 4 GB limit
  fi
}

# Compress function with pigz for faster compression
com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

echo "|| Compressing CCACHE ||"

# First compress in with pogz in a single zip.
time com ccache 1 # Compression level 1, its enough

# Now split in 2GB parts
7za a -tzip -v2048m -mx=1 ccache_backup.zip ccache.tar.gz

# upload all parts
echo "|| Uploading CCACHE ||"
for i in /tmp/ccache_backup.zip.*; do
   time up ${i}
done

sleep 5
echo "|| Uploaded ||"

# clean storage
rm -rf /tmp/*
